accounts/urls.py
from django.urls import path
from accounts.views import Register, UserLogin, confirm_email

app_name = 'accounts'

urlpatterns = [
    path('register/', Register.as_view(), name="signup"),
    path('login/', UserLogin.as_view(), name="login"),
    path('confirm_email/<int:id>/', confirm_email, name="email"),
]

emailConf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', 'accounts'))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

# Create your models here.
class UserProfileManager(BaseUserManager):

    def create_user(self, email, name, password=None):
        if not email:
            raise ValueError("User must have an email address!")
        
        email = self.normalize_email(email)
        user = self.model(name=name, email=email)

        user.set_password(password)
        user.is_superuser = False
        user.is_staff = False
        user.save(using=self._db)

        return user
    
    def create_superuser(self, name, email, password):
        user = self.create_user(email, name, password)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user
class UserProfile(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_staff = models.BooleanField(default=False)
    email_confirmed = models.BooleanField(default=False)

    objects = UserProfileManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return str(self.email)
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile

class UserProfileForm(UserCreationForm):
    class Meta:
        model = UserProfile
        fields = ['name', 'email', 'password1', 'password2']

accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserProfileForm
from .models import UserProfile
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.views.generic import FormView
from django.contrib.auth.views import LoginView
# Create your views here.


class Register(FormView):
    template_name = 'accounts/base.html'
    form_class = UserProfileForm
    success_url = '/login/'
    
    def form_valid(self, form):
        name = self.request.POST['name']
        email = self.request.POST['email']
        password = self.request.POST['password1']
        user = UserProfile.objects.create_user(name=name, email=email, password=password)
        html_message = render_to_string('accounts/send_email.html', {'id': user.pk})
        plain_message = strip_tags(html_message)
        from_email = 'From <from@example.com>'
        to = 'to@example.com'
        send_mail("Email confirmation", plain_message, from_email, [to], html_message=html_message)
        return super().form_valid(form)

def confirm_email(request, id):
    user = UserProfile.objects.get(pk=id)
    user.email_confirmed = True
    user.save()
    return redirect('accounts:login')


class UserLogin(LoginView):
    template_name = 'accounts/base.html'
    

accounts/templates/accounts/base.html
{% load i18n %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="{{ language }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Title{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'accounts:signup' %}">{% trans 'Signup' %}</a></li>
            <li><a href="{% url 'accounts:login' %}">{% trans 'Login' %}</a></li>
        </ul>
    </nav>
    <main>
        <form class="col-lg-5 col-md-8 mx-auto p-2" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-dark" type="submit">{% trans 'Submit' %}</button>
        </form>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

accounts/templates/accounts/email.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% trans 'Email confirm' %}</title>
</head>
<body>
    <h1>{% blocktrans %}Confirm your email{% endblocktrans %}</h1>
    <p>{% blocktrans %}Go to your gmail see if theres a message from us(if not check the spam){% endblocktrans %}</p> 
</body>
</html>

accounts/templates/accounts/send_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email confirmation</title>
</head>
<body>
    {% autoescape off %}
    <p>please confirm your email: </p>
    <a href="{% url 'accounts:email' id %}"></a>
    {% endautoescape %}
</body>
</html>